####################################################
#                  AUTOMATIONS                     #
####################################################
title: Automations
icon: mdi:home-automation
cards:
  - type: entities
    title: Climate
    show_header_toggle: false
    entities:
      - entity: automation.ecobee_fan_off
      - entity: automation.ecobee_fan_on
      - entity: automation.ecobee_set_to_auto
      - entity: automation.ecobee_set_to_off
      - entity: automation.ecobee_preset_mode_sleep
      - entity: automation.ecobee_preset_mode_resume
      - entity: automation.bedroom_fan_on_while_sleeping
      - entity: automation.bedroom_fan_off_while_sleeping
      - entity: automation.office_fan_on_while_occupied
      - entity: automation.office_fan_off_while_occupied


  - type: entities
    title: Lights
    show_header_toggle: false
    entities:
      - entity: automation.bedroom_lights_out_david_asleep
      - entity: automation.bedroom_lights_out_georgina_asleep
      - entity: automation.light_on_when_getting_home
      - entity: automation.lights_out_when_leaving
      - entity: automation.kitchen_on_in_the_evening
      - entity: automation.porch_light_on
      - entity: automation.dim_down_porch_light
      - entity: automation.sunrise_lighting_control
      - entity: automation.nightlight_for_dog
      - entity: automation.good_night_trigger
      # - entity: automation.garage_lights_on_by_motion
      # - entity: automation.garage_lights_off_by_motion
      - entity: automation.turn_on_off_garage_lights_when_there_is_movement
      - entity: automation.monthly_holiday_color_scene_on
        # name: C9's On at Sunset
        # icon: mdi:led-on
      - entity: automation.monthly_holiday_color_scene_off
        # name: C9's Off at Sunrise
        # icon: mdi:led-off
      - entity: automation.dinning_light_out
      # - entity: automation.office_light_out
      - entity: automation.patio_light_on_by_camera_sensor
      # - entity: automation.patio_light_off_by_camera_sensor
      # - entity: automation.side_light_off_by_sensor
      - entity: automation.side_light_on_by_sensor

  - type: entities
    title: Notification
    show_header_toggle: false
    entities:
      - entity: automation.hass_startup_notification
      - entity: automation.laundry_dryer_is_done
      - entity: automation.laundry_washer_is_done
      - entity: automation.georgina_is_home
      - entity: automation.david_is_home
      - entity: automation.georgina_leaving_work
      - entity: automation.tell_david_to_leave_for_work
      - entity: automation.wake_up_david_for_work
      # - entity: automation.michael_is_home
      - entity: automation.pond_filter_issue
      # - entity: automation.pond_filter_issue_for_mark
      - entity: automation.battery_is_low_in_sensor
      - entity: automation.deconz_lights_unavailable
      - entity: automation.update_available_notification
      - entity: automation.internet_speed_connection_poor
      - entity: automation.failed_login
      - entity: automation.persistent_check_config
      - entity: automation.notify_if_camera_is_offline
      # - entity: automation.notify_if_new_devices

  - type: entities
    title: Home Assistant
    show_header_toggle: false
    entities:
      - entity: automation.hassio_snapshot
      - entity: automation.lets_encrypt_cert_did_not_update
      - entity: automation.let_s_encrypt_renewal
      - entity: automation.set_theme_to_midnight

  - type: entities
    title: Holiday
    show_header_toggle: false
    entities:
      - entity: automation.christmas_tree_on_when_home
        name: Christmas Tree On When Home
        icon: mdi:pine-tree
      - entity: automation.christmas_tree_off_when_away
        name: Tree Off When Away
        icon: mdi:pine-tree

  - type: entities
    title: Other
    show_header_toggle: false
    entities:
      - entity: automation.reset_david_sleeping
      - entity: automation.reset_georgina_sleeping
      - entity: automation.georgina_is_awake
      - entity: automation.living_room_fan
      - entity: automation.master_bedroom_fan
      - entity: automation.office_fan
      - entity: automation.turn_on_vacation_mode
      - entity: automation.turn_off_vacation_mode
      - entity: automation.wallpanel_motion_clear
      - entity: automation.wallpanel_motion_detected
      - entity: automation.wallpanel_off_when_leaving

  - type: entities
    title: Dog
    show_header_toggle: false
    entities:
      - entity: automation.feed_the_dog_evening
      - entity: automation.feed_the_dog_morning_weekends
      - entity: automation.feed_the_dog_morning_weekdays
      - entity: automation.turn_off_pet_away_mode
      - entity: automation.turn_on_pet_away_mode